# Generated by Django 3.2.20 on 2023-07-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_nodeinfo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeinfo',
            name='time',
        ),
    ]
