# Generated by Django 3.2.20 on 2023-07-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledgeName', models.CharField(max_length=32)),
                ('relation', models.IntegerField()),
            ],
        ),
    ]
