# Generated by Django 3.2.20 on 2023-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(max_length=26)),
                ('target', models.TextField(max_length=26)),
                ('name', models.TextField(max_length=26)),
            ],
        ),
    ]
