# Generated by Django 3.2.20 on 2023-07-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_newnode_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.DeleteModel(
            name='NewNode',
        ),
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
