# Generated by Django 3.2.20 on 2023-07-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20230721_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
