# Generated by Django 3.2.20 on 2023-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20230721_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='favourite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
