# Generated by Django 3.2.20 on 2023-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_nodeinfo_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
