# Generated by Django 3.2.20 on 2023-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_nodeinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinfo',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
