# Generated by Django 3.2.20 on 2023-07-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_nodeinfo_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(max_length=114)),
                ('username', models.CharField(max_length=514)),
            ],
        ),
    ]
