# Generated by Django 3.2.20 on 2023-07-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='nodecount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
